// packages/config/src/abi/oddsXAbi.ts
export const oddsXAbi = [
  {
    type: "function",
    name: "createMarket",
    stateMutability: "nonpayable",
    inputs: [
      { name: "marketId", type: "bytes32" },
      { name: "description", type: "string" },
      { name: "endTime", type: "uint64" },
      { name: "outcomesCount", type: "uint32" },
      { name: "oracleAddress", type: "address" },
      { name: "asset", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getMarket",
    stateMutability: "view",
    inputs: [{ name: "marketId", type: "bytes32" }],
    outputs: [
      {
        name: "market",
        type: "tuple",
        components: [
          { name: "asset", type: "address" },
          { name: "endTime", type: "uint64" },
          { name: "outcomesCount", type: "uint32" },
          { name: "feeBps", type: "uint16" },
          { name: "state", type: "uint8" },
          { name: "oracle", type: "address" },
          { name: "winningOutcome", type: "uint32" },
          { name: "description", type: "string" },
          { name: "totalPool", type: "uint256" },
          { name: "winningPool", type: "uint256" },
          { name: "distributablePool", type: "uint256" },
          { name: "protocolFee", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getOutcomePool",
    stateMutability: "view",
    inputs: [
      { name: "marketId", type: "bytes32" },
      { name: "outcome", type: "uint32" },
    ],
    outputs: [{ name: "pool", type: "uint256" }],
  },
  {
    type: "function",
    name: "getUserStake",
    stateMutability: "view",
    inputs: [
      { name: "marketId", type: "bytes32" },
      { name: "user", type: "address" },
      { name: "outcome", type: "uint32" },
    ],
    outputs: [{ name: "stake", type: "uint256" }],
  },
  {
    type: "function",
    name: "previewReward",
    stateMutability: "view",
    inputs: [
      { name: "marketId", type: "bytes32" },
      { name: "user", type: "address" },
    ],
    outputs: [{ name: "reward", type: "uint256" }],
  },
  {
    type: "function",
    name: "hasClaimedReward",
    stateMutability: "view",
    inputs: [
      { name: "marketId", type: "bytes32" },
      { name: "user", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "hasRole",
    stateMutability: "view",
    inputs: [
      { name: "role", type: "bytes32" },
      { name: "account", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "placeBet",
    stateMutability: "payable",
    inputs: [
      { name: "marketId", type: "bytes32" },
      { name: "outcome", type: "uint32" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "claimReward",
    stateMutability: "nonpayable",
    inputs: [{ name: "marketId", type: "bytes32" }],
    outputs: [{ name: "reward", type: "uint256" }],
  },
  {
    type: "event",
    name: "MarketCreated",
    anonymous: false,
    inputs: [
      { name: "marketId", type: "bytes32", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "oracle", type: "address", indexed: true },
      { name: "asset", type: "address", indexed: false },
      { name: "endTime", type: "uint64", indexed: false },
      { name: "outcomesCount", type: "uint32", indexed: false },
      { name: "feeBps", type: "uint16", indexed: false },
      { name: "description", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "BetPlaced",
    anonymous: false,
    inputs: [
      { name: "marketId", type: "bytes32", indexed: true },
      { name: "bettor", type: "address", indexed: true },
      { name: "outcome", type: "uint32", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "newUserStake", type: "uint256", indexed: false },
      { name: "newOutcomePool", type: "uint256", indexed: false },
      { name: "newMarketPool", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "MarketResolved",
    anonymous: false,
    inputs: [
      { name: "marketId", type: "bytes32", indexed: true },
      { name: "winningOutcome", type: "uint32", indexed: true },
      { name: "resolver", type: "address", indexed: true },
      { name: "totalPool", type: "uint256", indexed: false },
      { name: "winningPool", type: "uint256", indexed: false },
      { name: "distributablePool", type: "uint256", indexed: false },
      { name: "protocolFee", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "MarketCancelled",
    anonymous: false,
    inputs: [
      { name: "marketId", type: "bytes32", indexed: true },
      { name: "cancelledBy", type: "address", indexed: true },
      { name: "reason", type: "bytes32", indexed: true },
    ],
  },
  {
    type: "event",
    name: "RewardClaimed",
    anonymous: false,
    inputs: [
      { name: "marketId", type: "bytes32", indexed: true },
      { name: "user", type: "address", indexed: true },
      { name: "winningOutcome", type: "uint32", indexed: true },
      { name: "winningStake", type: "uint256", indexed: false },
      { name: "reward", type: "uint256", indexed: false },
    ],
  },
] as const;
